[build]
builder = "nixpacks"

[deploy]
startCommand = "python src/main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
PORT = "5000"
PYTHONPATH = "/app"

